import { MenuData } from '@/store/menu-store';

/**
 * Mock menu data for initial page load
 * Follows exact schema from MenuGenerationResponse
 */
export const mockMenuData: MenuData = {
  id: 'mock-menu-001',
  staple_recommendations: 'Arroz blanco o integral (white or brown rice)',
  total_prep_time_minutes: 195,
  time_warning: false,
  items: [
    {
      id: 'mock-item-001',
      item_type: 'main',
      pairing_group: 'A',
      name_en: 'Korean Beef Bulgogi',
      name_es: 'Bulgogi de Res Coreano',
      cuisine: 'Korean',
      description: 'Tender marinated beef with soy, sesame, and ginger. Sweet, savory, and perfect for batch cooking.',
      prep_time_minutes: 40,
      servings: 4,
      sort_order: 0,
    },
    {
      id: 'mock-item-002',
      item_type: 'side',
      pairing_group: 'A',
      name_en: 'Sesame Cucumber Salad',
      name_es: 'Ensalada de Pepino con Ajonjolí',
      cuisine: 'Korean',
      description: 'Crisp cucumbers with sesame oil, rice vinegar, and chili flakes. Light, refreshing, and complements the bulgogi perfectly.',
      prep_time_minutes: 15,
      servings: 4,
      sort_order: 1,
    },
    {
      id: 'mock-item-003',
      item_type: 'main',
      pairing_group: 'B',
      name_en: 'Mediterranean Chicken with Olives',
      name_es: 'Pollo Mediterráneo con Aceitunas',
      cuisine: 'Mediterranean',
      description: 'Braised chicken thighs with tomatoes, olives, capers, and herbs. Rich, tangy, and perfect over couscous or pasta.',
      prep_time_minutes: 55,
      servings: 4,
      sort_order: 2,
    },
    {
      id: 'mock-item-004',
      item_type: 'side',
      pairing_group: 'B',
      name_en: 'Roasted Lemon Potatoes',
      name_es: 'Papas Asadas con Limón',
      cuisine: 'Mediterranean',
      description: 'Crispy roasted potatoes with lemon, garlic, and oregano. A classic Greek side that pairs beautifully with the chicken.',
      prep_time_minutes: 45,
      servings: 4,
      sort_order: 3,
    },
    {
      id: 'mock-item-005',
      item_type: 'breakfast',
      pairing_group: 'independent',
      name_en: 'Savory Egg Muffins',
      name_es: 'Muffins Salados de Huevo',
      cuisine: 'American',
      description: 'Make-ahead egg muffins with spinach, cheese, and bell peppers. Grab-and-go breakfast for busy mornings.',
      prep_time_minutes: 30,
      servings: 6,
      sort_order: 4,
    },
    {
      id: 'mock-item-006',
      item_type: 'drink',
      pairing_group: 'independent',
      name_en: 'Watermelon Lime Agua Fresca',
      name_es: 'Agua Fresca de Sandía con Limón',
      cuisine: 'Mexican',
      description: 'Refreshing blended watermelon with lime and a touch of sugar. Perfect for warm weather.',
      prep_time_minutes: 10,
      servings: 6,
      sort_order: 5,
    },
  ],
};
